
package Ventanas;

import Clases.Conexion;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public final class prueba extends javax.swing.JFrame {
     Conexion conexion;
     int xMouse, yMouse;
    /**
     * Creates new form prueba
     */
    public prueba() {
        initComponents();
        limpiar();
        bloquear();
        mostrar();
    }
    
    void limpiar(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtTel.setText("");
        txtCiudad.setText("");
        txtId.setText("");
    }
    
    void bloquear(){
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtTel.setEnabled(false);
        txtCiudad.setEnabled(false);
        nuevoBtn.setEnabled(true);
        guardarBtn.setEnabled(false);
        buscarBtn.setEnabled(false);
    
    }
    
    void desbloquear(){
        txtNombre.setEnabled(true);
        txtApellido.setEnabled(true);
        txtTel.setEnabled(true);
        txtCiudad.setEnabled(true);
        nuevoBtn.setEnabled(false);
        guardarBtn.setEnabled(true);
        buscarBtn.setEnabled(true);
    
    }
    
    public void mostrar(){
        
        conexion=new Conexion();
        Connection cn=conexion.getConexion();
        String sql=" SELECT * FROM usuario " ;
        Statement st;
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Telefono");
        model.addColumn("Ciudad");
        jTable.setModel(model);
        
        String datos[]= new String[5];
        
         try {
             
                 st=cn.createStatement();
                 ResultSet rs= st.executeQuery(sql);
                 while(rs.next()){
                     datos[0]=rs.getString(1);
                     datos[1]=rs.getString(2);
                     datos[2]=rs.getString(3);
                     datos[3]=rs.getString(4);
                     datos[4]=rs.getString(5);
                     model.addRow(datos);
                 }
                             
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"Error "+ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        linkBtnTxt = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JPanel();
        buscarBtnTxt = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JPanel();
        guardarBtnTxt = new javax.swing.JLabel();
        editarBtn = new javax.swing.JPanel();
        editarBtnTxt = new javax.swing.JLabel();
        eliminarBtn = new javax.swing.JPanel();
        eliminarBtnTxt = new javax.swing.JLabel();
        nuevoBtn = new javax.swing.JPanel();
        nuevoBtnTxt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg1.setBackground(new java.awt.Color(255, 255, 255));
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        bg1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido");
        bg1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Telefono");
        bg1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ciudad");
        bg1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 50, 30));

        txtCiudad.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        txtCiudad.setBorder(null);
        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });
        bg1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 170, 30));

        txtNombre.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        bg1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, 30));

        txtApellido.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        txtApellido.setBorder(null);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        bg1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, 30));

        txtTel.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        txtTel.setBorder(null);
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        bg1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, 30));

        txtId.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        txtId.setBorder(null);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        bg1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 60, 30));

        jTable.setBackground(new java.awt.Color(229, 229, 229));
        jTable.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable.setRowHeight(20);
        jScrollPane2.setViewportView(jTable);

        bg1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 460, 160));

        header.setBackground(new java.awt.Color(204, 0, 204));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(255, 0, 0));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        linkBtnTxt.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        linkBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        linkBtnTxt.setText("www.leonardozuluaga.com.co");
        linkBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkBtnTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(linkBtnTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        buscarBtn.setBackground(new java.awt.Color(204, 0, 204));
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBtnMouseClicked(evt);
            }
        });

        buscarBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        buscarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarBtnTxt.setText("BUSCAR");
        buscarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarBtnLayout = new javax.swing.GroupLayout(buscarBtn);
        buscarBtn.setLayout(buscarBtnLayout);
        buscarBtnLayout.setHorizontalGroup(
            buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarBtnLayout.createSequentialGroup()
                .addComponent(buscarBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buscarBtnLayout.setVerticalGroup(
            buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg1.add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, 30));

        guardarBtn.setBackground(new java.awt.Color(204, 0, 204));
        guardarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        guardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBtnMouseClicked(evt);
            }
        });

        guardarBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        guardarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        guardarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarBtnTxt.setText("GUARDAR");
        guardarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout guardarBtnLayout = new javax.swing.GroupLayout(guardarBtn);
        guardarBtn.setLayout(guardarBtnLayout);
        guardarBtnLayout.setHorizontalGroup(
            guardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guardarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        guardarBtnLayout.setVerticalGroup(
            guardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guardarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 80, 30));

        editarBtn.setBackground(new java.awt.Color(204, 0, 204));
        editarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarBtnMouseClicked(evt);
            }
        });

        editarBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        editarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        editarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editarBtnTxt.setText("EDITAR");
        editarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout editarBtnLayout = new javax.swing.GroupLayout(editarBtn);
        editarBtn.setLayout(editarBtnLayout);
        editarBtnLayout.setHorizontalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        editarBtnLayout.setVerticalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg1.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 80, 30));

        eliminarBtn.setBackground(new java.awt.Color(204, 0, 204));
        eliminarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarBtnMouseClicked(evt);
            }
        });

        eliminarBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        eliminarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminarBtnTxt.setText("ELIMINAR");
        eliminarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout eliminarBtnLayout = new javax.swing.GroupLayout(eliminarBtn);
        eliminarBtn.setLayout(eliminarBtnLayout);
        eliminarBtnLayout.setHorizontalGroup(
            eliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        eliminarBtnLayout.setVerticalGroup(
            eliminarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eliminarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg1.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 70, 30));

        nuevoBtn.setBackground(new java.awt.Color(204, 0, 204));
        nuevoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nuevoBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        nuevoBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        nuevoBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoBtnTxt.setText("NUEVO");
        nuevoBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevoBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout nuevoBtnLayout = new javax.swing.GroupLayout(nuevoBtn);
        nuevoBtn.setLayout(nuevoBtnLayout);
        nuevoBtnLayout.setHorizontalGroup(
            nuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        nuevoBtnLayout.setVerticalGroup(
            nuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg1.add(nuevoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 70, 30));

        jSeparator2.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 0, 204));
        bg1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 60, 10));

        jLabel6.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Id");
        bg1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 20, 30));

        jSeparator3.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 0, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 10, 150));

        jLabel5.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CRUD  & MySQL");
        bg1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 140, -1));

        jSeparator4.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator4.setForeground(new java.awt.Color(204, 0, 204));
        bg1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 460, 20));

        jSeparator5.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 0, 204));
        bg1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, 10));

        jSeparator6.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 0, 204));
        bg1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, 10));

        jSeparator7.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator7.setForeground(new java.awt.Color(204, 0, 204));
        bg1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, 10));

        jSeparator8.setBackground(new java.awt.Color(204, 0, 204));
        jSeparator8.setForeground(new java.awt.Color(204, 0, 204));
        bg1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 170, 10));

        jPanel1.setBackground(new java.awt.Color(99, 6, 99));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        bg1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 40, 390));

        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtNombre.transferFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        txtApellido.transferFocus();
            // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
        txtTel.transferFocus();
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
        txtCiudad.transferFocus();
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void nuevoBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoBtnTxtMouseClicked
        desbloquear();
        txtNombre.requestFocus();
    }//GEN-LAST:event_nuevoBtnTxtMouseClicked

    private void nuevoBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoBtnTxtMouseEntered
        //nuevoBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_nuevoBtnTxtMouseEntered

    private void nuevoBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoBtnTxtMouseExited
        //nuevoBtn.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_nuevoBtnTxtMouseExited

    private void buscarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnTxtMouseClicked
        conexion=new Conexion();
        Connection cn=conexion.getConexion();
        String sql="", id;
        
        id=txtId.getText();
        
        sql="SELECT * FROM usuario WHERE id=?";
        
        try{
            PreparedStatement psd = (PreparedStatement) cn.prepareStatement(sql);
            psd.setInt(1, Integer.parseInt(id));
            
            ResultSet a=psd.executeQuery();
            if(a.next()){
                JOptionPane.showMessageDialog(null,"Registro encontrado");
                txtNombre.setText(a.getString("nombre"));
                txtApellido.setText(a.getString("apellido"));
                txtTel.setText(a.getString("telefono"));
                txtCiudad.setText(a.getString("ciudad"));
                
                
            }else{
                JOptionPane.showMessageDialog(null,"Registro no encontrado. \n"
                        + "El ID '"+id+"' no existe.");
                
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error "+ex+". Debe Ingresar el ID para poder buscar.");            
        }
    }//GEN-LAST:event_buscarBtnTxtMouseClicked

    private void buscarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBtnTxtMouseEntered

    private void buscarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnTxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBtnTxtMouseExited

    private void buscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseClicked
        
    }//GEN-LAST:event_buscarBtnMouseClicked

    private void guardarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnTxtMouseClicked
        conexion=new Conexion();
        Connection cn=conexion.getConexion();
        String nombre, apellido, tel, ciu;
        String sql="";
        
        nombre=txtNombre.getText();
        apellido=txtApellido.getText();
        tel=txtTel.getText();
        ciu=txtCiudad.getText();
        sql="INSERT INTO usuario (nombre,apellido,telefono,ciudad) VALUES (?,?,?,?)";
        try{
            PreparedStatement psd = (PreparedStatement) cn.prepareStatement(sql);
            psd.setString(1, nombre);
            psd.setString(2, apellido);
            psd.setString(3, tel);
            psd.setString(4, ciu);
            int a=psd.executeUpdate();
            if(a>0){
                JOptionPane.showMessageDialog(null,"Registro guardado");
                limpiar();
                bloquear();
                mostrar();
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error "+ex);
            limpiar();
        }
    }//GEN-LAST:event_guardarBtnTxtMouseClicked

    private void guardarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarBtnTxtMouseEntered

    private void guardarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnTxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarBtnTxtMouseExited

    private void guardarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseClicked
        
    }//GEN-LAST:event_guardarBtnMouseClicked

    private void eliminarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnTxtMouseClicked
        conexion=new Conexion();
        Connection cn=conexion.getConexion();
        String sql="", id;
        
        id=txtId.getText();
        
        sql="DELETE FROM usuario WHERE id=?";
        
        try{
            PreparedStatement psd = (PreparedStatement) cn.prepareStatement(sql);
            psd.setInt(1, Integer.parseInt(id));
            
            int a=psd.executeUpdate();
            if(a>0){
                JOptionPane.showMessageDialog(null,"Registro borrado"); 
                limpiar();
                mostrar();
            }else{
                JOptionPane.showMessageDialog(null,"Registro no encontrado");
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error "+ex);            
        }
    }//GEN-LAST:event_eliminarBtnTxtMouseClicked

    private void eliminarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBtnTxtMouseEntered

    private void eliminarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnTxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBtnTxtMouseExited

    private void eliminarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnMouseClicked
        
    }//GEN-LAST:event_eliminarBtnMouseClicked

    private void editarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnTxtMouseClicked
        conexion=new Conexion();
        Connection cn=conexion.getConexion();
        String nombre, apellido, tel, ciu, id;
        String sql="";
        
        nombre=txtNombre.getText();
        apellido=txtApellido.getText();
        tel=txtTel.getText();
        ciu=txtCiudad.getText();
        id=txtId.getText();
        
        sql="UPDATE usuario SET nombre=?, apellido=?, telefono=?, ciudad=? WHERE id=?";
        try{
            PreparedStatement psd = (PreparedStatement) cn.prepareStatement(sql);
            psd.setString(1, nombre);
            psd.setString(2, apellido);
            psd.setString(3, tel);
            psd.setString(4, ciu);
            psd.setInt(5, Integer.parseInt(id));
            
            int a=psd.executeUpdate();
            if(a>0){
                JOptionPane.showMessageDialog(null,"Registro modificado");
                limpiar();
                bloquear();
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error "+ex);
            limpiar();
        }
    }//GEN-LAST:event_editarBtnTxtMouseClicked

    private void editarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_editarBtnTxtMouseEntered

    private void editarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnTxtMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_editarBtnTxtMouseExited

    private void editarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMouseClicked
        
    }//GEN-LAST:event_editarBtnMouseClicked

    private void linkBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkBtnTxtMouseClicked
        try {

            Desktop.getDesktop().browse(new URI("https://www.leonardozuluaga.com.co"));

        } catch (URISyntaxException ex) {

            System.out.println(ex);

        }catch(IOException e){

            System.out.println(e);

        }
    }//GEN-LAST:event_linkBtnTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg1;
    private javax.swing.JPanel buscarBtn;
    private javax.swing.JLabel buscarBtnTxt;
    private javax.swing.JPanel editarBtn;
    private javax.swing.JLabel editarBtnTxt;
    private javax.swing.JPanel eliminarBtn;
    private javax.swing.JLabel eliminarBtnTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel guardarBtn;
    private javax.swing.JLabel guardarBtnTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel linkBtnTxt;
    private javax.swing.JPanel nuevoBtn;
    private javax.swing.JLabel nuevoBtnTxt;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
